---
version: "3.4"
services:
  server:
    build: ./server
    ports:
      # allow override of published port
      - "127.0.0.1:${EXTERNAL_PORT:-9000}:8000"
  client:
    build: .
    ports:
      - "127.0.0.1:${EXTERNAL_PORT:-9001}:3000"
    env_file:
      - app.env